version: 2.1

orbs:
  artifactory: circleci/artifactory@1.0.0

workflows:
  version: 2
  build_and_push:
    jobs:
    - patch_hold:
        type: approval
        context: circleci-build-context
    - patch_push:
        context: circleci-build-context
        repo-env: dev
        requires:
          - patch_hold

jobs:
  patch_push:
    parameters:
      repo-env:
        type: string
        default: dev
    environment:
      PYPI_REPOSITORY: finance-pypi-<< parameters.repo-env >>
      PYPI_REPOSITORY_URL: monacohq.jfrog.io/artifactory/api/pypi/finance-pypi-<< parameters.repo-env >>
    docker:
      - image: cimg/python:3.10.2
    working_directory: ~/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - "91:f5:2b:8f:a7:6c:66:ab:5f:fa:16:52:e6:cb:ea:15"
      - checkout
      - run:
          name: Install CI dependencies
          command: pip install -r ci-requirements.txt --extra-index-url https://${ARTIFACTORY_USER}:${ARTIFACTORY_API_KEY}@$PYPI_REPOSITORY_URL/simple
      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers = $PYPI_REPOSITORY" >> ~/.pypirc
            echo -e "[$PYPI_REPOSITORY]" >> ~/.pypirc
            echo -e "repository: https://$PYPI_REPOSITORY_URL" >> ~/.pypirc
            echo -e "username: $ARTIFACTORY_USER" >> ~/.pypirc
            echo -e "password: $ARTIFACTORY_API_KEY" >> ~/.pypirc
            cat ~/.pypirc
      - run:
          name: Build and Publish
          command: |
            chmod 755 ./deploy.sh
            make deploy
      #- run:
      #    name: Build library
      #    command: python3 setup.py bdist_wheel
      #- run:
      #    name: Publish
      #    command: twine upload -r $PYPI_REPOSITORY dist/*